// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6ukuUfED_swTUbPPeMscmy00D77kfAA',
    appId: '1:19844553607:web:648abce1dc6d6580349122',
    messagingSenderId: '19844553607',
    projectId: 'authentication-7c9e5',
    authDomain: 'authentication-7c9e5.firebaseapp.com',
    storageBucket: 'authentication-7c9e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFXggdIHhlFy_4MPIbxpLPTZbLOhH8_Ow',
    appId: '1:19844553607:android:8e8eb3c60cde9b3e349122',
    messagingSenderId: '19844553607',
    projectId: 'authentication-7c9e5',
    storageBucket: 'authentication-7c9e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaE2XIzqKAw39kYPh8J2_dhw5OONGBuiE',
    appId: '1:19844553607:ios:2bbdad37c18bb7ea349122',
    messagingSenderId: '19844553607',
    projectId: 'authentication-7c9e5',
    storageBucket: 'authentication-7c9e5.appspot.com',
    iosBundleId: 'com.example.flutterWidgets',
  );
}
